---
- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: eksctl_temp_dir

- name: Download eksctl
  block:
    - name: Download eksctl
      ansible.builtin.get_url:
        url: https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
        dest: "{{ eksctl_temp_dir.path }}/eksctl.tar.gz"
        mode: "0644"

    - name: Unzip eksctl
      ansible.builtin.unarchive:
        src: "{{ eksctl_temp_dir.path }}/eksctl.tar.gz"
        dest: "{{ eksctl_temp_dir.path }}"
        remote_src: true

    - name: Install eksctl
      become: true
      ansible.builtin.copy:
        src: "{{ eksctl_temp_dir.path }}/eksctl"
        dest: /usr/local/bin/eksctl
        mode: "0755"
        remote_src: true

  always:
    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "{{ eksctl_temp_dir.path }}"
        state: absent

- name: Add eksctl completion to bash
  become: true
  ansible.builtin.copy:
    dest: /etc/bash_completion.d/eksctl
    content: |
      #!/bin/bash
      source <(eksctl completion bash)
    mode: "0644"
