all:
  vars:
    ansible_user: ubuntu
    #ansible_ssh_private_key_file: "{{ local_setup_private_key_file.dest }}"
    #home_key_pair_name: "{{ home_key_pair_name }}"
  children:
    servers:
      hosts:
  hosts:
    # 下記warning回避のためのダミーエントリ。実際のホストはロールlocal_setupのtasksでadd_hostモジュールを使用してserversグループへ追加する。
    # [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
    dummy_host:
